# Yazi Wallust Dynamic Theme
[mgr]
cwd = { fg = "{{color6}}" }
hovered = { fg = "{{background}}", bg = "{{color4}}" }
preview_hovered = { underline = true }
find_keyword = { fg = "{{color3}}", bold = true, italic = true }
find_position = { fg = "{{color5}}", bold = true }
marker_copied = { fg = "{{color2}}", bg = "{{color2}}" }
marker_cut = { fg = "{{color1}}", bg = "{{color1}}" }
marker_selected = { fg = "{{color4}}", bg = "{{color4}}" }
tab_active = { fg = "{{background}}", bg = "{{color4}}" }
tab_inactive = { fg = "{{foreground}}", bg = "{{color0}}" }
count_copied = { fg = "{{background}}", bg = "{{color2}}" }
count_cut = { fg = "{{background}}", bg = "{{color1}}" }
count_selected = { fg = "{{background}}", bg = "{{color4}}" }
border_symbol = "│"
border_style = { fg = "{{color8}}" }
